groups:
  - name: ErrorAlert
    rules:
      - alert: "On API down"
        expr: up{job="api_gateway"} < 1
        for: 30s
      - alert: "On mongodb down"
        expr: up{job="mongodb"} < 1
        for: 10s
