global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: "api_gateway"
    static_configs:
      - targets: ["api_gateway:3054"]